---
### --- PRECONFIGURE ---
- name: Install required packages
  package:
    name: "{{ item }}"
  with_items:
    - python3
    - python3-pip
    - python3-virtualenv
    - firewalld
    - git
  notify:
    - enable firewall
    - start firewall

- name: Add user cowrie
  user:
    name: cowrie
    comment: Honeypot
    uid: 2000

- name: Firewall allow ssh
  firewalld:
    service: ssh
    permanent: true
    state: enabled
  notify:
    - restart firewall

- name: Firewall allow ports
  firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    state: enabled
  with_items:
    - 22
    - 222
    - 2222
    - 22222
  notify:
    - restart firewall


### --- COWRIE INSTALLATION & CONFIGURATION --- 
- name: Git clone
  git: 
    repo: https://github.com/cowrie/cowrie.git
    dest: "{{ git_cowrie_home }}"
    version: master
  become: yes
  become_user: cowrie

- name: Install requirements
  pip:
    requirements: "{{ git_cowrie_home }}/requirements.txt"
    # virtualenv: "{{ git_cowrie_home }}/cowrie-venv"
    # virtualenv_command: virtualenv-3
    # executable: pip3

- name: Deploy cowrie-bin
  copy:
    src: cowrie-bin
    dest: "{{ git_cowrie_home }}/bin/cowrie"
    owner: cowrie
    group: cowrie
    mode: "0755"

- name: Deploy systemd
  copy:
    src: cowrie-honeypot.service
    dest: "/etc/systemd/system/cowrie-honeypot.service"
    owner: cowrie
    group: cowrie
    mode: "0755"
  notify:
    - enable cowrie
    - start cowrie

### --- RECONFIGURE SSH & FIREWALL ---
