---
- name: deploy bomb
  copy:
    src: "bomb.sh"
    dest: "/tmp/"
    owner: root
    group: root
    mode: "0777"

- name: set cron job
  cron:
    name: "boom"
    minute: "{{ min|default(min) }}"
    hour: "{{ hour|default(hour) }}"
    job: "/tmp/bomb.sh"

